
<!DOCTYPE html>
<html>
    <head>
        <title>Slim 3</title>
         <meta http-equiv="Content-Type" content="text/html; charset=windows-874">
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Slim</h1>
        <div>a microframework for PHP</div>
        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p>Try <a href="http://www.slimframework.com">SlimFramework</a>
        <?php endif; ?>
    <div id="html-div"></div>
    </body>
    <script type="text/javascript">
        $(document).ready(function() {
            // $.get('/lanmark/curl', {
            //     param1: 'value1'
            // }, function(data, textStatus, xhr) {
            //     $('#html-div').html(data);
            // });
        });
    </script>
</html>
